zhiyiyuemiao:
  #  【必填】省
  province: "广西壮族自治区"
  #  【选填】市
  city: "贵港市"
  #  区（可以不用填，不打算开发此功能）
  district: ""
  #  【必填】抢购疫苗的类型（必填），务必与小程序上的名称一致
  productName: "九价人乳头瘤病毒疫苗"
  #  【必填】预约地点名称(必填),务必与小程序上的名称一致
  customerName: "贵港市平南县疾病预防控制中心门诊"
  #  【必填】预约时间
  subscribeTime: "2023-03-19 19:59:40"
  #  【必填】疫苗可预约的月份
  month: 202103
  #  【必填】生日
  birthday: "1999-04-28"
  #  【必填】电话
  tel: "xxxx"
  #  【必填】性别：1为男性 2为女性
  sex: 2
  #  【必填】姓名
  name: "xxx"
  #  【必填】身份证号
  idcard: "xxx"
  #  【必填】这个Cookie需要抓包获取 【有效期为5分钟或更久】
  cookie: "ASP.NET_SessionId=xxx"
